### ISSUE TITLE
Roomba Completion

### ISSUE THREAD

**Issue by Omvk97** [Omvk97/SemesterProjectBigData#16]
- [x] Create HBase client for saving images
- [x] Delete Kafka connection
- [x] Benyt sig af geojson fremfor shapefiles
- [X] Support for downloading for multiple geojsons (multiple nature area monitoring) (passed as argument from scheduler)

**Comment by SofieLouise** [comment]
This might be useful to get the scheduler to work:
https://www.randydeng.com/programming/2019/07/01/queuing-asynchronous-jobs-with-rq-docker-and-supervisor.html

**Comment by SofieLouise** [comment]
I've worked as much on Roomba as I could by myself. I didn't quite finish the implementation. 

I've made it possible for Roomba to take multiple geojson paths as input. If none is given it uses the standard geodata.json file already provided in the Docker environment.

Removed Kafka connection.

Using geojsons instead of shapefiles: Generalized the implemementation, so all geo files can be used - including geojsons and shapefiles.

I've updated the HBase implementation so it connects to the 
The scheduler doesn't work, because the rq worker and rqscheduler commands aren't found - even though I just installed them using pip. 

I would be helpful, if we can take a look at the problems together later today in the workshop.
